// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flipdot.proto

package flipdot

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LightRequest_Status int32

const (
	LightRequest_UNSPECIFIED LightRequest_Status = 0
	LightRequest_ON          LightRequest_Status = 1
	LightRequest_OFF         LightRequest_Status = 2
)

var LightRequest_Status_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "ON",
	2: "OFF",
}

var LightRequest_Status_value = map[string]int32{
	"UNSPECIFIED": 0,
	"ON":          1,
	"OFF":         2,
}

func (x LightRequest_Status) String() string {
	return proto.EnumName(LightRequest_Status_name, int32(x))
}

func (LightRequest_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_37483730bdf40ffc, []int{7, 0}
}

type GetInfoResponse struct {
	Signs                []*GetInfoResponse_SignInfo `protobuf:"bytes,1,rep,name=signs,proto3" json:"signs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37483730bdf40ffc, []int{0}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetSigns() []*GetInfoResponse_SignInfo {
	if m != nil {
		return m.Signs
	}
	return nil
}

type GetInfoResponse_SignInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse_SignInfo) Reset()         { *m = GetInfoResponse_SignInfo{} }
func (m *GetInfoResponse_SignInfo) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse_SignInfo) ProtoMessage()    {}
func (*GetInfoResponse_SignInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_37483730bdf40ffc, []int{0, 0}
}

func (m *GetInfoResponse_SignInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse_SignInfo.Unmarshal(m, b)
}
func (m *GetInfoResponse_SignInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse_SignInfo.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse_SignInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse_SignInfo.Merge(m, src)
}
func (m *GetInfoResponse_SignInfo) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse_SignInfo.Size(m)
}
func (m *GetInfoResponse_SignInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse_SignInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse_SignInfo proto.InternalMessageInfo

func (m *GetInfoResponse_SignInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetInfoResponse_SignInfo) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *GetInfoResponse_SignInfo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_37483730bdf40ffc, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DrawRequest struct {
	Sign                 int32    `protobuf:"varint,1,opt,name=sign,proto3" json:"sign,omitempty"`
	Image                []byte   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawRequest) Reset()         { *m = DrawRequest{} }
func (m *DrawRequest) String() string { return proto.CompactTextString(m) }
func (*DrawRequest) ProtoMessage()    {}
func (*DrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37483730bdf40ffc, []int{2}
}

func (m *DrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawRequest.Unmarshal(m, b)
}
func (m *DrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawRequest.Marshal(b, m, deterministic)
}
func (m *DrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawRequest.Merge(m, src)
}
func (m *DrawRequest) XXX_Size() int {
	return xxx_messageInfo_DrawRequest.Size(m)
}
func (m *DrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DrawRequest proto.InternalMessageInfo

func (m *DrawRequest) GetSign() int32 {
	if m != nil {
		return m.Sign
	}
	return 0
}

func (m *DrawRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type DrawResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawResponse) Reset()         { *m = DrawResponse{} }
func (m *DrawResponse) String() string { return proto.CompactTextString(m) }
func (*DrawResponse) ProtoMessage()    {}
func (*DrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37483730bdf40ffc, []int{3}
}

func (m *DrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawResponse.Unmarshal(m, b)
}
func (m *DrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawResponse.Marshal(b, m, deterministic)
}
func (m *DrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawResponse.Merge(m, src)
}
func (m *DrawResponse) XXX_Size() int {
	return xxx_messageInfo_DrawResponse.Size(m)
}
func (m *DrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DrawResponse proto.InternalMessageInfo

func (m *DrawResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type StartTestRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTestRequest) Reset()         { *m = StartTestRequest{} }
func (m *StartTestRequest) String() string { return proto.CompactTextString(m) }
func (*StartTestRequest) ProtoMessage()    {}
func (*StartTestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37483730bdf40ffc, []int{4}
}

func (m *StartTestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTestRequest.Unmarshal(m, b)
}
func (m *StartTestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTestRequest.Marshal(b, m, deterministic)
}
func (m *StartTestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTestRequest.Merge(m, src)
}
func (m *StartTestRequest) XXX_Size() int {
	return xxx_messageInfo_StartTestRequest.Size(m)
}
func (m *StartTestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartTestRequest proto.InternalMessageInfo

type StartTestResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTestResponse) Reset()         { *m = StartTestResponse{} }
func (m *StartTestResponse) String() string { return proto.CompactTextString(m) }
func (*StartTestResponse) ProtoMessage()    {}
func (*StartTestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37483730bdf40ffc, []int{5}
}

func (m *StartTestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTestResponse.Unmarshal(m, b)
}
func (m *StartTestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTestResponse.Marshal(b, m, deterministic)
}
func (m *StartTestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTestResponse.Merge(m, src)
}
func (m *StartTestResponse) XXX_Size() int {
	return xxx_messageInfo_StartTestResponse.Size(m)
}
func (m *StartTestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartTestResponse proto.InternalMessageInfo

func (m *StartTestResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type StopTestResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopTestResponse) Reset()         { *m = StopTestResponse{} }
func (m *StopTestResponse) String() string { return proto.CompactTextString(m) }
func (*StopTestResponse) ProtoMessage()    {}
func (*StopTestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37483730bdf40ffc, []int{6}
}

func (m *StopTestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopTestResponse.Unmarshal(m, b)
}
func (m *StopTestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopTestResponse.Marshal(b, m, deterministic)
}
func (m *StopTestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopTestResponse.Merge(m, src)
}
func (m *StopTestResponse) XXX_Size() int {
	return xxx_messageInfo_StopTestResponse.Size(m)
}
func (m *StopTestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopTestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopTestResponse proto.InternalMessageInfo

func (m *StopTestResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type LightRequest struct {
	Status               LightRequest_Status `protobuf:"varint,1,opt,name=status,proto3,enum=LightRequest_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LightRequest) Reset()         { *m = LightRequest{} }
func (m *LightRequest) String() string { return proto.CompactTextString(m) }
func (*LightRequest) ProtoMessage()    {}
func (*LightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37483730bdf40ffc, []int{7}
}

func (m *LightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightRequest.Unmarshal(m, b)
}
func (m *LightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightRequest.Marshal(b, m, deterministic)
}
func (m *LightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightRequest.Merge(m, src)
}
func (m *LightRequest) XXX_Size() int {
	return xxx_messageInfo_LightRequest.Size(m)
}
func (m *LightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LightRequest proto.InternalMessageInfo

func (m *LightRequest) GetStatus() LightRequest_Status {
	if m != nil {
		return m.Status
	}
	return LightRequest_UNSPECIFIED
}

type LightResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LightResponse) Reset()         { *m = LightResponse{} }
func (m *LightResponse) String() string { return proto.CompactTextString(m) }
func (*LightResponse) ProtoMessage()    {}
func (*LightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37483730bdf40ffc, []int{8}
}

func (m *LightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightResponse.Unmarshal(m, b)
}
func (m *LightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightResponse.Marshal(b, m, deterministic)
}
func (m *LightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightResponse.Merge(m, src)
}
func (m *LightResponse) XXX_Size() int {
	return xxx_messageInfo_LightResponse.Size(m)
}
func (m *LightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LightResponse proto.InternalMessageInfo

func (m *LightResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterEnum("LightRequest_Status", LightRequest_Status_name, LightRequest_Status_value)
	proto.RegisterType((*GetInfoResponse)(nil), "GetInfoResponse")
	proto.RegisterType((*GetInfoResponse_SignInfo)(nil), "GetInfoResponse.SignInfo")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*DrawRequest)(nil), "DrawRequest")
	proto.RegisterType((*DrawResponse)(nil), "DrawResponse")
	proto.RegisterType((*StartTestRequest)(nil), "StartTestRequest")
	proto.RegisterType((*StartTestResponse)(nil), "StartTestResponse")
	proto.RegisterType((*StopTestResponse)(nil), "StopTestResponse")
	proto.RegisterType((*LightRequest)(nil), "LightRequest")
	proto.RegisterType((*LightResponse)(nil), "LightResponse")
}

func init() { proto.RegisterFile("flipdot.proto", fileDescriptor_37483730bdf40ffc) }

var fileDescriptor_37483730bdf40ffc = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x25, 0xed, 0x92, 0xae, 0xb7, 0xed, 0x96, 0x5d, 0x4d, 0x53, 0x08, 0x3c, 0x54, 0x46, 0x42,
	0x15, 0x1a, 0x2e, 0x64, 0x9a, 0xf8, 0x00, 0xd6, 0xa2, 0x4a, 0xd3, 0x86, 0x1c, 0xf8, 0x80, 0x8c,
	0xba, 0x49, 0xa4, 0x25, 0x0e, 0xb1, 0xab, 0x89, 0xbf, 0xe0, 0x6b, 0x79, 0x46, 0xb6, 0x13, 0xd4,
	0x06, 0x21, 0x95, 0x37, 0xdf, 0xe3, 0x7b, 0x8e, 0xaf, 0xef, 0x39, 0x30, 0xd9, 0x3c, 0xe6, 0xd5,
	0x5a, 0x28, 0x5a, 0xd5, 0x42, 0x89, 0xf0, 0x45, 0x2a, 0x44, 0xfa, 0xc8, 0xe7, 0xa6, 0x7a, 0xd8,
	0x6e, 0xe6, 0xbc, 0xa8, 0xd4, 0x0f, 0x7b, 0x49, 0x7e, 0x3a, 0x70, 0xfa, 0x89, 0xab, 0x55, 0xb9,
	0x11, 0x8c, 0xcb, 0x4a, 0x94, 0x92, 0xe3, 0x1c, 0x5c, 0x99, 0xa7, 0xa5, 0x0c, 0x9c, 0x69, 0x7f,
	0x36, 0x8a, 0x9e, 0xd3, 0x4e, 0x03, 0x8d, 0xf3, 0xb4, 0x34, 0x80, 0xed, 0x0b, 0x6f, 0xe1, 0xb8,
	0x85, 0x10, 0xe1, 0xa8, 0x4c, 0x0a, 0x1e, 0x38, 0x53, 0x67, 0x36, 0x64, 0xe6, 0x8c, 0xe7, 0xe0,
	0x3e, 0xe5, 0x6b, 0x95, 0x05, 0xbd, 0xa9, 0x33, 0x73, 0x99, 0x2d, 0xf0, 0x02, 0xbc, 0x8c, 0xe7,
	0x69, 0xa6, 0x82, 0xbe, 0x81, 0x9b, 0x8a, 0x5c, 0x83, 0xbb, 0xa8, 0x6b, 0x51, 0x6b, 0xa9, 0x6f,
	0x62, 0x6d, 0xa5, 0x5c, 0x66, 0xce, 0x18, 0xc0, 0xa0, 0xe0, 0x52, 0x26, 0x29, 0x37, 0x62, 0x43,
	0xd6, 0x96, 0xe4, 0x03, 0x8c, 0x6e, 0xea, 0xe4, 0x89, 0xf1, 0xef, 0x5b, 0x2e, 0x95, 0x26, 0xeb,
	0xe1, 0x5a, 0xb2, 0x3e, 0xeb, 0x39, 0xf2, 0xa2, 0xa5, 0x8e, 0x99, 0x2d, 0xc8, 0x25, 0x8c, 0x2d,
	0xb1, 0xf9, 0xfe, 0x4b, 0x70, 0xb9, 0x7e, 0xdf, 0x50, 0x47, 0x91, 0x47, 0xcd, 0x34, 0xcc, 0x82,
	0x04, 0xc1, 0x8f, 0x55, 0x52, 0xab, 0x2f, 0x5c, 0xaa, 0xe6, 0x2d, 0xf2, 0x1e, 0xce, 0x76, 0xb0,
	0x83, 0x64, 0xde, 0x69, 0x19, 0x51, 0xfd, 0x07, 0x23, 0x83, 0xf1, 0xad, 0xde, 0x4f, 0xfb, 0xc1,
	0x4b, 0xf0, 0xa4, 0x4a, 0xd4, 0x56, 0x9a, 0xf6, 0x93, 0xe8, 0x9c, 0xee, 0x5e, 0xd3, 0xd8, 0xdc,
	0xb1, 0xa6, 0x87, 0xbc, 0x01, 0xcf, 0x22, 0x78, 0x0a, 0xa3, 0xaf, 0x77, 0xf1, 0xe7, 0xc5, 0xc7,
	0xd5, 0x72, 0xb5, 0xb8, 0xf1, 0x9f, 0xa1, 0x07, 0xbd, 0xfb, 0x3b, 0xdf, 0xc1, 0x01, 0xf4, 0xef,
	0x97, 0x4b, 0xbf, 0x47, 0xde, 0xc2, 0xa4, 0x91, 0x3a, 0x64, 0xb0, 0xe8, 0x97, 0x03, 0x83, 0xa5,
	0x4d, 0x1c, 0x5e, 0xc1, 0xa0, 0x09, 0x0b, 0x5e, 0x50, 0x9b, 0x3b, 0xda, 0xe6, 0x8e, 0x2e, 0x74,
	0xee, 0x42, 0xbf, 0x1b, 0x27, 0x7c, 0x05, 0x47, 0xda, 0x00, 0x1c, 0xd3, 0x1d, 0x03, 0xc3, 0x09,
	0xdd, 0x73, 0x25, 0x82, 0xe1, 0x9f, 0x1d, 0xe3, 0x19, 0xed, 0x7a, 0x10, 0x22, 0xfd, 0xdb, 0x82,
	0x6b, 0x38, 0x6e, 0x97, 0xfc, 0xcf, 0x71, 0xb4, 0x54, 0xc7, 0x87, 0xd7, 0xe0, 0x9a, 0xff, 0xe3,
	0x64, 0x6f, 0xa5, 0xe1, 0x09, 0xdd, 0x5b, 0xcb, 0x83, 0x67, 0xa4, 0xae, 0x7e, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x0b, 0x4d, 0xf0, 0xda, 0x70, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FlipdotClient is the client API for Flipdot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlipdotClient interface {
	GetInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetInfoResponse, error)
	Draw(ctx context.Context, in *DrawRequest, opts ...grpc.CallOption) (*DrawResponse, error)
	StartTest(ctx context.Context, in *StartTestRequest, opts ...grpc.CallOption) (*StartTestResponse, error)
	StopTest(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StopTestResponse, error)
	Light(ctx context.Context, in *LightRequest, opts ...grpc.CallOption) (*LightResponse, error)
}

type flipdotClient struct {
	cc *grpc.ClientConn
}

func NewFlipdotClient(cc *grpc.ClientConn) FlipdotClient {
	return &flipdotClient{cc}
}

func (c *flipdotClient) GetInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, "/Flipdot/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flipdotClient) Draw(ctx context.Context, in *DrawRequest, opts ...grpc.CallOption) (*DrawResponse, error) {
	out := new(DrawResponse)
	err := c.cc.Invoke(ctx, "/Flipdot/Draw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flipdotClient) StartTest(ctx context.Context, in *StartTestRequest, opts ...grpc.CallOption) (*StartTestResponse, error) {
	out := new(StartTestResponse)
	err := c.cc.Invoke(ctx, "/Flipdot/StartTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flipdotClient) StopTest(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StopTestResponse, error) {
	out := new(StopTestResponse)
	err := c.cc.Invoke(ctx, "/Flipdot/StopTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flipdotClient) Light(ctx context.Context, in *LightRequest, opts ...grpc.CallOption) (*LightResponse, error) {
	out := new(LightResponse)
	err := c.cc.Invoke(ctx, "/Flipdot/Light", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlipdotServer is the server API for Flipdot service.
type FlipdotServer interface {
	GetInfo(context.Context, *empty.Empty) (*GetInfoResponse, error)
	Draw(context.Context, *DrawRequest) (*DrawResponse, error)
	StartTest(context.Context, *StartTestRequest) (*StartTestResponse, error)
	StopTest(context.Context, *empty.Empty) (*StopTestResponse, error)
	Light(context.Context, *LightRequest) (*LightResponse, error)
}

func RegisterFlipdotServer(s *grpc.Server, srv FlipdotServer) {
	s.RegisterService(&_Flipdot_serviceDesc, srv)
}

func _Flipdot_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlipdotServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Flipdot/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlipdotServer).GetInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flipdot_Draw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlipdotServer).Draw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Flipdot/Draw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlipdotServer).Draw(ctx, req.(*DrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flipdot_StartTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlipdotServer).StartTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Flipdot/StartTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlipdotServer).StartTest(ctx, req.(*StartTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flipdot_StopTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlipdotServer).StopTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Flipdot/StopTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlipdotServer).StopTest(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flipdot_Light_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlipdotServer).Light(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Flipdot/Light",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlipdotServer).Light(ctx, req.(*LightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Flipdot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Flipdot",
	HandlerType: (*FlipdotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Flipdot_GetInfo_Handler,
		},
		{
			MethodName: "Draw",
			Handler:    _Flipdot_Draw_Handler,
		},
		{
			MethodName: "StartTest",
			Handler:    _Flipdot_StartTest_Handler,
		},
		{
			MethodName: "StopTest",
			Handler:    _Flipdot_StopTest_Handler,
		},
		{
			MethodName: "Light",
			Handler:    _Flipdot_Light_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flipdot.proto",
}
